theme: jekyll-theme-cayman
total: "4.942.826"
diario: "25.137"
obitos: "146.826"
obitosdiario: "375"
totalms: "4.927.235"
diarioms: "11.946"
obitosms: "146.675"
obitosdiarioms: "323"
dataref: "05/10/2020"
