theme: jekyll-theme-cayman
total: "8.138.400"
diario: "29.647"
obitos: "203.706"
obitosdiario: "482"
totalms: "8.131.612"
diarioms: "25.822"
obitosms: "203.580"
obitosdiarioms: "480"
dataref: "11/01/2021"
