theme: jekyll-theme-cayman
total: "4.545.884"
diario: "15.591"
obitos: "136.947"
obitosdiario: "331"
totalms: "4.544.629"
diarioms: "16.389"
obitosms: "136.895"
obitosdiarioms: "363"
dataref: "20/09/2020"
