theme: jekyll-theme-cayman
total: "5.634.727"
diario: "16.784"
obitos: "162.095"
obitosdiario: "246"
totalms: "5.631.181"
diarioms: "18.862"
obitosms: "162.015"
obitosdiarioms: "279"
dataref: "06/11/2020"
