theme: jekyll-theme-cayman
total: "9.838.427"
diario: "21.986"
obitos: "239.376"
obitosdiario: "627"
totalms: "9.834.513"
diarioms: "24.759"
obitosms: "239.245"
obitosdiarioms: "713"
dataref: "14/02/2021"
