theme: jekyll-theme-cayman
total: "3.766.452"
diario: "40.021"
obitos: "118.772"
obitosdiario: "933"
totalms: "3.761.391"
diarioms: "44.235"
obitosms: "118.649"
obitosdiarioms: "984"
dataref: "27/08/2020"
