theme: jekyll-theme-cayman
total: "3.675.999"
diario: "46.633"
obitos: "116.710"
obitosdiario: "1.207"
totalms: "3.669.995"
diarioms: "47.134"
obitosms: "116.580"
obitosdiarioms: "1.271"
dataref: "25/08/2020"
