theme: jekyll-theme-cayman
total: "5.328.124"
diario: "23.531"
obitos: "156.020"
obitosdiario: "484"
totalms: "5.323.630"
diarioms: "24.858"
obitosms: "155.900"
obitosdiarioms: "497"
dataref: "22/10/2020"
