theme: jekyll-theme-cayman
total: "9.403.854"
diario: "56.151"
obitos: "228.991"
obitosdiario: "1.260"
totalms: "9.396.293"
diarioms: "56.873"
obitosms: "228.795"
obitosdiarioms: "1.232"
dataref: "04/02/2021"
