theme: jekyll-theme-cayman
total: "8.519.252"
diario: "26.849"
obitos: "210.434"
obitosdiario: "441"
totalms: "8.511.770"
diarioms: "23.671"
obitosms: "210.299"
obitosdiarioms: "452"
dataref: "18/01/2021"
