theme: jekyll-theme-cayman
total: "5.864.724"
diario: "13.335"
obitos: "165.873"
obitosdiario: "134"
totalms: "5.863.093"
diarioms: "14.134"
obitosms: "165.798"
obitosdiarioms: "140"
dataref: "15/11/2020"
