theme: jekyll-theme-cayman
total: "4.097.641"
diario: "49.039"
obitos: "125.664"
obitosdiario: "848"
totalms: "4.092.832"
diarioms: "51.194"
obitosms: "125.521"
obitosdiarioms: "907"
dataref: "04/09/2020"
