theme: jekyll-theme-cayman
total: "4.423.815"
diario: "37.475"
obitos: "134.225"
obitosdiario: "968"
totalms: "4.419.083"
diarioms: "36.820"
obitosms: "134.106"
obitosdiarioms: "987"
dataref: "16/09/2020"
