theme: jekyll-theme-cayman
total: "3.863.611"
diario: "13.340"
obitos: "120.935"
obitosdiario: "360"
totalms: "3.862.311"
diarioms: "16.158"
obitosms: "120.828"
obitosdiarioms: "366"
dataref: "30/08/2020"
