theme: jekyll-theme-cayman
total: "6.090.828"
diario: "16.767"
obitos: "169.602"
obitosdiario: "336"
totalms: "6.087.608"
diarioms: "16.207"
obitosms: "169.485"
obitosdiarioms: "302"
dataref: "23/11/2020"
