theme: jekyll-theme-cayman
total: "4.242.735"
diario: "39.160"
obitos: "129.698"
obitosdiario: "978"
totalms: "4.238.446"
diarioms: "40.557"
obitosms: "129.522"
obitosdiarioms: "983"
dataref: "10/09/2020"
