theme: jekyll-theme-cayman
total: "7.816.071"
diario: "54.518"
obitos: "197.862"
obitosdiario: "1.120"
totalms: "7.810.400"
diarioms: "56.648"
obitosms: "197.732"
obitosdiarioms: "1.171"
dataref: "05/01/2021"
