theme: jekyll-theme-cayman
total: "6.440.063"
diario: "46.113"
obitos: "174.599"
obitosdiario: "646"
totalms: "6.436.650"
diarioms: "49.863"
obitosms: "174.515"
obitosdiarioms: "698"
dataref: "02/12/2020"
