theme: jekyll-theme-cayman
total: "4.386.340"
diario: "34.709"
obitos: "133.257"
obitosdiario: "1.092"
totalms: "4.382.263"
diarioms: "36.653"
obitosms: "133.119"
obitosdiarioms: "1.113"
dataref: "15/09/2020"
