theme: jekyll-theme-cayman
total: "3.912.579"
diario: "48.968"
obitos: "121.562"
obitosdiario: "627"
totalms: "3.908.272"
diarioms: "45.961"
obitosms: "121.381"
obitosdiarioms: "553"
dataref: "31/08/2020"
