theme: jekyll-theme-cayman
total: "4.048.602"
diario: "45.161"
obitos: "124.816"
obitosdiario: "890"
totalms: "4.041.638"
diarioms: "43.773"
obitosms: "124.614"
obitosdiarioms: "834"
dataref: "03/09/2020"
