theme: jekyll-theme-cayman
total: "4.149.381"
diario: "8.893"
obitos: "127.047"
obitosdiario: "297"
totalms: "4.147.794"
diarioms: "10.273"
obitosms: "126.960"
obitosdiarioms: "310"
dataref: "07/09/2020"
