theme: jekyll-theme-cayman
total: "8.878.795"
diario: "28.461"
obitos: "217.831"
obitosdiario: "649"
totalms: "8.871.393"
diarioms: "26.816"
obitosms: "217.664"
obitosdiarioms: "627"
dataref: "25/01/2021"
