theme: jekyll-theme-cayman
total: "7.879.824"
diario: "63.753"
obitos: "199.121"
obitosdiario: "1.259"
totalms: "7.873.830"
diarioms: "63.430"
obitosms: "198.974"
obitosdiarioms: "1.242"
dataref: "06/01/2021"
