theme: jekyll-theme-cayman
total: "5.665.852"
diario: "9.965"
obitos: "162.475"
obitosdiario: "127"
totalms: "5.664.115"
diarioms: "10.554"
obitosms: "162.397"
obitosdiarioms: "128"
dataref: "08/11/2020"
