theme: jekyll-theme-cayman
total: "8.261.849"
diario: "56.663"
obitos: "206.101"
obitosdiario: "1.226"
totalms: "8.256.536"
diarioms: "60.899"
obitosms: "205.964"
obitosdiarioms: "1.274"
dataref: "13/01/2021"
