theme: jekyll-theme-cayman
total: "5.443.459"
diario: "28.252"
obitos: "158.039"
obitosdiario: "513"
totalms: "5.439.641"
diarioms: "29.787"
obitosms: "157.946"
obitosdiarioms: "549"
dataref: "27/10/2020"
