theme: jekyll-theme-cayman
total: "9.064.942"
diario: "59.362"
obitos: "221.756"
obitosdiario: "1.427"
totalms: "9.058.687"
diarioms: "61.811"
obitosms: "221.547"
obitosdiarioms: "1.386"
dataref: "28/01/2021"
