theme: jekyll-theme-cayman
total: "4.203.575"
diario: "34.785"
obitos: "128.720"
obitosdiario: "1.125"
totalms: "4.197.889"
diarioms: "35.816"
obitosms: "128.539"
obitosdiarioms: "1.075"
dataref: "09/09/2020"
