theme: jekyll-theme-cayman
total: "3.957.398"
diario: "44.819"
obitos: "122.731"
obitosdiario: "1.169"
totalms: "3.950.931"
diarioms: "42.659"
obitosms: "122.596"
obitosdiarioms: "1.215"
dataref: "01/09/2020"
