theme: jekyll-theme-cayman
total: "3.629.366"
diario: "20.907"
obitos: "115.503"
obitosdiario: "669"
totalms: "3.622.861"
diarioms: "17.078"
obitosms: "115.309"
obitosdiarioms: "565"
dataref: "24/08/2020"
