theme: jekyll-theme-cayman
total: "4.351.631"
diario: "18.640"
obitos: "132.165"
obitosdiario: "419"
totalms: "4.345.610"
diarioms: "15.155"
obitosms: "132.006"
obitosdiarioms: "381"
dataref: "14/09/2020"
