theme: jekyll-theme-cayman
total: "8.019.495"
diario: "52.173"
obitos: "201.578"
obitosdiario: "941"
totalms: "8.013.708"
diarioms: "52.035"
obitosms: "201.460"
obitosdiarioms: "962"
dataref: "08/01/2021"
