theme: jekyll-theme-cayman
total: "4.317.982"
diario: "29.781"
obitos: "131.322"
obitosdiario: "748"
totalms: "4.315.687"
diarioms: "33.523"
obitosms: "131.210"
obitosdiarioms: "814"
dataref: "12/09/2020"
