theme: jekyll-theme-cayman
total: "4.003.441"
diario: "46.043"
obitos: "123.926"
obitosdiario: "1.195"
totalms: "3.997.865"
diarioms: "46.934"
obitosms: "123.780"
obitosdiarioms: "1.184"
dataref: "02/09/2020"
