theme: jekyll-theme-cayman
total: "5.950.295"
diario: "33.522"
obitos: "167.557"
obitosdiario: "741"
totalms: "5.945.849"
diarioms: "34.091"
obitosms: "167.455"
obitosdiarioms: "756"
dataref: "18/11/2020"
