theme: jekyll-theme-cayman
total: "8.330.747"
diario: "68.898"
obitos: "207.251"
obitosdiario: "1.150"
totalms: "8.324.294"
diarioms: "67.758"
obitosms: "207.095"
obitosdiarioms: "1.131"
dataref: "14/01/2021"
