theme: jekyll-theme-cayman
total: "7.967.322"
diario: "87.498"
obitos: "200.637"
obitosdiario: "1.516"
totalms: "7.961.673"
diarioms: "87.843"
obitosms: "200.498"
obitosdiarioms: "1.524"
dataref: "07/01/2021"
