theme: jekyll-theme-cayman
total: "7.486.211"
diario: "16.694"
obitos: "191.223"
obitosdiario: "310"
totalms: "7.484.285"
diarioms: "18.479"
obitosms: "191.139"
obitosdiarioms: "344"
dataref: "27/12/2020"
