theme: jekyll-theme-cayman
total: "8.108.753"
diario: "27.659"
obitos: "203.224"
obitosdiario: "455"
totalms: "8.105.790"
diarioms: "29.792"
obitosms: "203.100"
obitosdiarioms: "469"
dataref: "10/01/2021"
